name: pydmqmc
channels:
  - conda-forge
  - defaults
dependencies:
  - coverage
  - mpi4py
  - numba
  - numpydoc
  - numpy
  - pip
  - pytest
  - ruff
  - scipy
  - sphinx
  - sphinx_rtd_theme
  - sphinxcontrib-bibtex
  - sympy
  - pip:
    - mpi-pytest
    - pytest-lazy-fixtures
